import QtQuick
import QtQuick.Controls.Basic
import QtQuick.Layouts

// A Qt Quick UI over C++ objects whose QMetaObject was generated by reflection, no moc.
// Everything it touches (counter, worker, controller) is plain C++26.
ApplicationWindow {
    id: win
    visible: true
    width: 900
    height: 620
    title: "reflect-moc: Qt Quick without moc"
    color: "#12161d"

    readonly property color card: "#1b212b"
    readonly property color accent: "#4cc2a1"
    readonly property color muted: "#8b98a9"

    ListModel { id: events }
    function note(text) {
        events.insert(0, { line: text })
        if (events.count > 14) events.remove(14, events.count - 14)
    }

    // QML sees the signals by name and reads their arguments by parameter name
    Connections {
        target: counter
        function onValueChanged(value) { win.note("Counter.valueChanged(value=" + value + ")") }
        function onLabelChanged(label) { win.note("Counter.labelChanged(label=\"" + label + "\")") }
    }
    Connections {
        target: controller
        function onProgress(percent, text) {
            bar.value = percent / 100
            win.note("Worker.progress(percent=" + percent + ", text=\"" + text + "\")   queued from the worker thread")
        }
        function onFinished(steps) { win.note("Worker.finished(steps=" + steps + ")") }
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 18
        spacing: 14

        Text {
            text: "Qt Quick on reflect-moc"
            color: "white"
            font.pixelSize: 26
            font.bold: true
        }
        Text {
            text: "No moc ran. The C++ classes below get their QMetaObject from C++26 reflection."
            color: win.muted
            font.pixelSize: 14
        }

        RowLayout {
            spacing: 14
            Layout.fillWidth: true

            // ---- Counter: property, slots, invokable, signals ----
            Rectangle {
                color: win.card
                radius: 10
                Layout.fillWidth: true
                Layout.preferredHeight: 230
                ColumnLayout {
                    anchors.fill: parent
                    anchors.margins: 16
                    spacing: 10
                    Text { text: "Counter  (property value, label)"; color: win.accent; font.pixelSize: 15; font.bold: true }
                    Text { text: counter.value; color: "white"; font.pixelSize: 64; font.bold: true }
                    RowLayout {
                        spacing: 8
                        Layout.fillWidth: true
                        Button { text: "-1"; Layout.fillWidth: true; Layout.preferredWidth: 1; onClicked: counter.add(-1) }
                        Button { text: "+1"; Layout.fillWidth: true; Layout.preferredWidth: 1; onClicked: counter.add(1) }
                        Button { text: "+10"; Layout.fillWidth: true; Layout.preferredWidth: 1; onClicked: counter.add(10) }
                        Button { text: "reset"; Layout.fillWidth: true; Layout.preferredWidth: 1; onClicked: counter.reset() }
                    }
                    RowLayout {
                        spacing: 8
                        Layout.fillWidth: true
                        Text { text: "label"; color: win.muted }
                        TextField {
                            Layout.fillWidth: true
                            Layout.preferredWidth: 1
                            text: counter.label
                            placeholderText: "type here: writes the label property"
                            onTextEdited: counter.label = text
                        }
                    }
                }
            }

            // ---- Worker: signals queued across threads ----
            Rectangle {
                color: win.card
                radius: 10
                Layout.fillWidth: true
                Layout.preferredHeight: 230
                ColumnLayout {
                    anchors.fill: parent
                    anchors.margins: 16
                    spacing: 12
                    Text { text: "Worker on its own QThread"; color: win.accent; font.pixelSize: 15; font.bold: true }
                    ProgressBar {
                        id: bar
                        Layout.fillWidth: true
                        value: 0
                        background: Rectangle { implicitHeight: 10; radius: 5; color: "#2a3342" }
                        contentItem: Item {
                            Rectangle { width: bar.visualPosition * parent.width; height: parent.height; radius: 5; color: win.accent }
                        }
                    }
                    Text {
                        text: controller.busy ? "running... progress signals arrive queued on the main thread" : "idle"
                        color: win.muted
                    }
                    Button {
                        text: "Run 8 steps"
                        enabled: !controller.busy
                        onClicked: { bar.value = 0; controller.start(8) }
                    }
                }
            }
        }

        // ---- the QMetaObject as Qt reports it ----
        Rectangle {
            color: win.card
            radius: 10
            Layout.fillWidth: true
            Layout.preferredHeight: 92
            ColumnLayout {
                anchors.fill: parent
                anchors.margins: 12
                spacing: 4
                Text { text: "QMetaObject, read back through Qt's own API"; color: win.accent; font.pixelSize: 13; font.bold: true }
                Text { text: controller.describe("Counter"); color: "white"; font.pixelSize: 12; font.family: "DejaVu Sans Mono"; wrapMode: Text.Wrap; Layout.fillWidth: true }
                Text { text: controller.describe("Worker"); color: "white"; font.pixelSize: 12; font.family: "DejaVu Sans Mono"; wrapMode: Text.Wrap; Layout.fillWidth: true }
            }
        }

        // ---- live signal log ----
        Rectangle {
            color: win.card
            radius: 10
            Layout.fillWidth: true
            Layout.fillHeight: true
            ListView {
                anchors.fill: parent
                anchors.margins: 10
                clip: true
                model: events
                delegate: Text { text: line; color: "#cfd8e3"; font.pixelSize: 12; font.family: "DejaVu Sans Mono" }
                header: Text { text: "signals as they fire"; color: win.muted; font.pixelSize: 12 }
            }
        }
    }
}
