// Generated by tools/rqt-migrate. With moc gone, qmltyperegistrar has no
// metatypes to read, so the QML_ELEMENT family is registered here instead.
#pragma once

#include <QtQml/qqml.h>

#include "birthdayparty.h"
#include "happybirthdaysong.h"
#include "person.h"

inline void rqt_register_qml_types()
{
    qmlRegisterAnonymousType<BirthdayPartyAttached>("People", 1);
    qmlRegisterType<BirthdayParty>("People", 1, 0, "BirthdayParty");
    qmlRegisterType<HappyBirthdaySong>("People", 1, 0, "HappyBirthdaySong");
    qmlRegisterAnonymousType<ShoeDescription>("People", 1);
    qmlRegisterUncreatableType<Person>("People", 1, 0, "Person", "Person is an abstract base class.");
    qmlRegisterType<Boy>("People", 1, 0, "Boy");
    qmlRegisterType<Girl>("People", 1, 0, "Girl");
}
