"""What rqt-migrate did, and what it left for a person."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field

AUTO = "auto"  # rewritten; nothing left to do
PARTIAL = "partial"  # rewritten, but behaviour differs from moc or needs a library feature
MANUAL = "manual"  # left as it was; a person must port it


@dataclass(frozen=True)
class Item:
    path: str
    line: int  # 1-based; 0 when the item is about the whole file
    construct: str
    status: str
    detail: str = ""


@dataclass
class Report:
    items: list[Item] = field(default_factory=list)

    def add(self, path: str, line: int, construct: str, status: str, detail: str = "") -> None:
        self.items.append(Item(path, line, construct, status, detail))

    def auto(self, path: str, line: int, construct: str, detail: str = "") -> None:
        self.add(path, line, construct, AUTO, detail)

    def partial(self, path: str, line: int, construct: str, detail: str) -> None:
        self.add(path, line, construct, PARTIAL, detail)

    def manual(self, path: str, line: int, construct: str, detail: str) -> None:
        self.add(path, line, construct, MANUAL, detail)

    def of_status(self, status: str) -> list[Item]:
        return [i for i in self.items if i.status == status]

    def counts(self) -> Counter:
        return Counter(i.status for i in self.items)


def diff_stats(diff: str) -> tuple[int, int, int]:
    """(files, added, removed) of a unified diff."""
    files = added = removed = 0
    for line in diff.splitlines():
        if line.startswith("+++ "):
            files += 1
        elif line.startswith("+") and not line.startswith("+++"):
            added += 1
        elif line.startswith("-") and not line.startswith("---"):
            removed += 1
    return files, added, removed


def render(title: str, report: Report, diff: str) -> str:
    files, added, removed = diff_stats(diff)
    counts = report.counts()
    by_construct = Counter(i.construct for i in report.items if i.status != MANUAL)
    lines = [
        f"# rqt-migrate report: {title}",
        "",
        "Generated by `tools/rqt-migrate`; do not edit. The target syntax is documented in",
        "`include/reflect_moc/qt/README.md` and spelled in `tools/rqt_migrate/syntax.py`.",
        "",
        f"Summary: {files} files changed, +{added} -{removed} lines; "
        f"{counts[AUTO]} constructs migrated automatically, {counts[PARTIAL]} partially, "
        f"{counts[MANUAL]} left for manual work.",
        "",
        "## Migrated",
        "",
        "| construct | count |",
        "|---|---|",
    ]
    lines += [f"| {construct} | {n} |" for construct, n in sorted(by_construct.items())]
    lines += ["", "## Needs attention", ""]
    attention = [i for i in report.items if i.status != AUTO]
    if not attention:
        lines.append("Nothing: every construct was migrated automatically.")
    else:
        lines += ["| where | construct | status | what remains |", "|---|---|---|---|"]
        for i in sorted(attention, key=lambda i: (i.status != MANUAL, i.path, i.line)):
            where = f"`{i.path}:{i.line}`" if i.line else f"`{i.path}`"
            detail = i.detail.replace("|", "\\|")
            lines.append(f"| {where} | {i.construct} | {i.status} | {detail} |")
    lines.append("")
    return "\n".join(lines)
