"""Every spelling rqt-migrate emits, in one place.

The reflect-moc Qt syntax is provisional until include/reflect_moc/qt/README.md
fixes it. When it changes, change it here and regenerate the ported examples;
no other module spells reflect-moc C++ or CMake.
"""

from __future__ import annotations

# The header every migrated header includes.
HEADER_INCLUDE = "#include <reflect_moc/qt.hpp>"

# Q_OBJECT also declared tr() with the class name as translation context. A
# class whose own code calls tr() gets this instead, so its context is kept.
TR_FUNCTIONS = "Q_DECLARE_TR_FUNCTIONS({cls})"
TR_INCLUDE = "#include <QtCore/qcoreapplication.h>"


def object_base(qt_base: str) -> str:
    """The base that replaces a Q_OBJECT class's first base (a mixin, not CRTP)."""
    return f"rqt::Object<{qt_base}>"


def object_base_using(qt_base: str) -> str:
    """Replaces `using QObject::QObject;`: inheriting constructors must name a direct base."""
    return f"using {object_base(qt_base)}::Object;"


# Per-class lines some base shapes need (spike 07's non-template base needs a
# staticMetaObject declaration in the class and its definition after it, for
# qobject_cast and pointer-to-member connect). {cls} is the class name. The
# first list replaces the Q_OBJECT line; the second follows the class's `};`.
CLASS_BODY_LINES: list[str] = []
AFTER_CLASS_LINES: list[str] = []

SIGNAL = "[[=rqt::signal]]"
SLOT = "[[=rqt::slot]]"
INVOKABLE = "[[=rqt::invokable]]"
GADGET = "[[=rqt::gadget]]"


def signal_body(arg_names: list[str]) -> str:
    """The one-line body of a migrated signal declaration."""
    return "{ rqt::emit{this}(" + ", ".join(arg_names) + "); }"


def enum(is_flag: bool, flags_name: str | None) -> str:
    """The annotation on the enum a Q_ENUM / Q_FLAG named.

    Q_FLAG(Options) names the QFlags alias; the annotation goes on the enum
    behind it and carries the alias name, which reflection cannot recover.
    """
    if not is_flag:
        return "[[=rqt::enum_]]"
    if flags_name:
        return f'[[=rqt::flag{{"{flags_name}"}}]]'
    return "[[=rqt::flag]]"


def property(fields: list[tuple[str, str]]) -> str:
    """The annotation on a property's READ accessor or MEMBER data member.

    fields is an ordered list of (designator, C++ value) pairs, e.g.
    [("write", '"setValue"'), ("notify", '"valueChanged"')]. The names are
    plain string literals, which GCC 16.2 accepts in an annotation and clang
    rejects (spike 02); for clang, wrap them in std::define_static_string here.
    """
    if not fields:
        return "[[=rqt::property{}]]"
    inner = ", ".join(f".{name} = {value}" for name, value in fields)
    return f"[[=rqt::property{{{inner}}}]]"


def classinfo(name_literal: str, value_literal: str) -> str:
    """A class annotation from Q_CLASSINFO; both arguments are C++ literals as written."""
    return f"[[=rqt::classinfo{{{name_literal}, {value_literal}}}]]"


def interface(name: str) -> str:
    """A class annotation from one Q_INTERFACES entry."""
    return f"[[=rqt::interface{{^^{name}}}]]"


# Spellings QT_NO_KEYWORDS takes away.
FOREVER = "for (;;)"
FOREACH = "Q_FOREACH"

# QML registration that qmltyperegistrar generated from moc's JSON.
QML_HEADER = "rqt_qml_types.hpp"
QML_FUNCTION = "rqt_register_qml_types"


def qml_register(kind: str, cls: str, uri: str, major: int, minor: int, name: str, reason: str | None) -> str:
    if kind == "anonymous":
        return f'qmlRegisterAnonymousType<{cls}>("{uri}", {major});'
    if kind == "uncreatable":
        return f'qmlRegisterUncreatableType<{cls}>("{uri}", {major}, {minor}, "{name}", {reason});'
    return f'qmlRegisterType<{cls}>("{uri}", {major}, {minor}, "{name}");'


def qml_header(includes: list[str], registrations: list[str]) -> str:
    lines = [
        "// Generated by tools/rqt-migrate. With moc gone, qmltyperegistrar has no",
        "// metatypes to read, so the QML_ELEMENT family is registered here instead.",
        "#pragma once",
        "",
        "#include <QtQml/qqml.h>",
        "",
        *[f'#include "{inc}"' for inc in includes],
        "",
        f"inline void {QML_FUNCTION}()",
        "{",
        *[f"    {r}" for r in registrations],
        "}",
        "",
    ]
    return "\n".join(lines)


QML_CALL = f"{QML_FUNCTION}();"

# CMake: inserted after qt_standard_project_setup() (or find_package(Qt6)).
CMAKE_BLOCK = """\
# rqt-migrate: reflect-moc builds the meta-objects from C++26 reflection, so
# moc must not run.
set(CMAKE_AUTOMOC OFF)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_compile_definitions(QT_NO_KEYWORDS)
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-freflection>)
include_directories({include_path})
"""


def cmake_include_path(relative_or_absolute: str, is_absolute: bool) -> str:
    if is_absolute:
        return relative_or_absolute
    return "${CMAKE_CURRENT_SOURCE_DIR}/" + relative_or_absolute

# Added to qt_add_qml_module: there is no moc JSON to generate qmltypes from.
CMAKE_QML_NO_TYPES = "NO_GENERATE_QMLTYPES"
